### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by joingenor** [react-designer/react-designer#41]
When I try to install te react-designer i get this error:
ReferenceError: Unknown plugin "@babel/plugin-proposal-export-default-from"

**Comment by DaveTheCrane** [comment]
I get the same. I've managed to get something working. These are the steps I've taken, in case they're useful to anyone else who wants to mess around with this library. The end result is very nice by the way, best out of the box SVG tool for react that I've come across. So although the install was frustrating, thanks for all the code! :)

I'm running on macosx Mojave, with `node v12.8.0` (installed via `brew`), `npm/npx 6.10.3`, on a freshly-created `create-react-app` project. 

I can bash my way through to a working example as follows:

*Error 1*
From `npm i react-designer` output:
```
> react-designer@1.1.1 prepare /Users/davcrane/dev/experiments/sketcher/node_modules/react-designer
> babel -d lib/ src/

sh: babel: command not found
```
fixed by `npm install @babel/cli @babel/core --save-dev`

NB don't use `npm install babel-cli babel-core --save-dev`, that installs babel v6.x, not v7.x

giving:
```
$ babel --version
7.5.5 (@babel/core 7.5.5)
```

*Error 2*
From `npm i react-designer` output:
```
ReferenceError: Unknown plugin "@babel/plugin-proposal-export-default-from" specified in "/Users/davcrane/dev/experiments/sketcher/node_modules/react-designer/.babelrc" at 0, attempted to resolve relative to "/Users/davcrane/dev/experiments/sketcher/node_modules/react-designer"
    at /Users/davcrane/dev/experiments/sketcher/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
```
fixed by `npm i @babel/plugin-proposal-export-default-from --save-dev`

*Error 3*
From `npm i react-designer` output:
```
Error: Cannot find module 'babel-plugin-css-modules-transform' from '/Users/davcrane/dev/experiments/sketcher/node_modules/react-designer'
    at Function.module.exports [as sync] (/Users/davcrane/dev/experiments/sketcher/node_modules/resolve/lib/sync.js:74:15)
```
fixed by `npm i babel-plugin-css-modules-transform --save-dev`

At this point, `npm i` exits successfully, and I have `react-designer 1.1.1` in my `package.json` file. Running `npm run start` gives me the vanilla `create-react-app` SVG spinner page in the browser.

*Error 4*
Now, I try to use the designer, by modifying `App.js` as follows:

```
import React from 'react';
import logo from './logo.svg';
import './App.css';
import Designer, {Text, Rect} from 'react-designer';

function App() {

  const objects = [
    {type: "text", x: 10, y: 20, text: "Hello!", fill: "red"},
    {type: "rect", x: 50, y: 70, width: 30, height: 40, fill: "red"}
  ];

  return (
    <div className="App">
      <Designer width={500} height={500}
                objectTypes={{
                  'text': Text,
                  'rect': Rect
                }}
                onUpdate={(objects) => console.log("update", objects)}
                objects={objects} />
    </div>
  );
}

export default App;
```

and `npm run start` fails to compile:

```
Failed to compile.

./node_modules/react-designer/lib/panels/ImagePanel.js
Module not found: Can't resolve 'react-dropzone' in '/Users/davcrane/dev/experiments/sketcher/node_modules/react-designer/lib/panels'
```
fixed by `npm install react-dropzone`

*Error 5*
`npm run start` now gives me:
```
Uncaught TypeError: Cannot read property 'split' of undefined
    at va (webfontloader.js:592)
    at Ea.push../node_modules/webfontloader/webfontloader.js.Ea.load (webfontloader.js:717)
    at pa (webfontloader.js:513)
```

Looks like a bug in the Text object type - if I remove that from `App.js`, so it only loads `Rect`, then I get a working app, with a red rectangle that I can move around and resize, and the "add" sidebar on the left allowing me to add more rectangles. Which is enough for me to get on with tinkering at what I'm doing, but there's definitely something broken here that needs looking at.

Full code for the working `App.js` here:
```
import React, { useState } from 'react';
import logo from './logo.svg';
import './App.css';
import Designer, {Rect} from 'react-designer';

function App() {

  const [objects, setObjects] = useState([
    {type: "rect", x: 50, y: 70, width: 30, height: 40, fill: "red"}
  ]);

  return (
    <div className="App">
      <Designer width={500} height={500}
                objectTypes={{
                  'rect': Rect
                }}
                onUpdate={(objects) => {
                    console.log("update", objects);
                    return setObjects(objects);
                }}
                objects={objects} />
    </div>
  );
}

export default App;
```

**Comment by DaveTheCrane** [comment]
Just adding a bit more detail here. I found that i got additional errors when I tried to add the Circle type into the sketcher, which looked like it was trying to modify the babel settings. In a `create-react-app` project, these are managed by the scripts, and can't be modified without ejecting the project. So I created a new project, ejected it and then tried to run `npm i react-designer` on that. 

I get the same error as i did previously - can't find `babel` from the shell, so it looks like it isn't CRA that's the source of the problem

**Comment by blueken** [comment]
I fixed it now. Thanks to  @DaveTheCrane 
`
npm i -D @babel/cli @babel/core  @babel/plugin-proposal-export-default-from babel-plugin-css-modules-transform
`

**Comment by capaj** [comment]
@blueken @DaveTheCrane the problem is your text object is missing `fontFamily` key. Will open a PR to fix that.

**Comment by Hyllesen** [comment]
This has been the most difficult to install package ever

**Comment by ahamal** [comment]
For something that looks quite straightforward this package is really an ordeal to install.
I'm stuck at `Requires Babel "^7.0.0-0", but was loaded with "6.26.3".`
